//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_user_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::admin_roles::Entity",
        from = "Column::RoleId",
        to = "super::admin_roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AdminRoles,
    #[sea_orm(
        belongs_to = "super::admin_users::Entity",
        from = "Column::UserId",
        to = "super::admin_users::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AdminUsers,
}

impl Related<super::admin_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminRoles.def()
    }
}

impl Related<super::admin_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
