//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub code: String,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::admin_role_permissions::Entity")]
    AdminRolePermissions,
    #[sea_orm(has_many = "super::admin_user_roles::Entity")]
    AdminUserRoles,
}

impl Related<super::admin_role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminRolePermissions.def()
    }
}

impl Related<super::admin_user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminUserRoles.def()
    }
}

impl Related<super::admin_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::admin_role_permissions::Relation::AdminPermissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::admin_role_permissions::Relation::AdminRoles
                .def()
                .rev(),
        )
    }
}

impl Related<super::admin_users::Entity> for Entity {
    fn to() -> RelationDef {
        super::admin_user_roles::Relation::AdminUsers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::admin_user_roles::Relation::AdminRoles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
