//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_menus")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub parent_id: Option<i64>,
    pub permission_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::admin_permissions::Entity",
        from = "Column::PermissionCode",
        to = "super::admin_permissions::Column::Code",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AdminPermissions,
}

impl Related<super::admin_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminPermissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
