//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app_permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub parent_code: Option<String>,
    pub sort: i32,
    pub kind: String,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCode",
        to = "Column::Code",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::app_role_permissions::Entity")]
    AppRolePermissions,
}

impl Related<super::app_role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRolePermissions.def()
    }
}

impl Related<super::app_roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_role_permissions::Relation::AppRoles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::app_role_permissions::Relation::AppPermissions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
