//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app_user_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_roles::Entity",
        from = "Column::RoleId",
        to = "super::app_roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppRoles,
    #[sea_orm(
        belongs_to = "super::app_users::Entity",
        from = "Column::UserId",
        to = "super::app_users::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppUsers,
}

impl Related<super::app_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRoles.def()
    }
}

impl Related<super::app_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
