//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(unique)]
    pub display_id: String,
    pub display_name: String,
    pub remark: Option<String>,
    pub status: String,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_user_roles::Entity")]
    AppUserRoles,
}

impl Related<super::app_user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUserRoles.def()
    }
}

impl Related<super::app_roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_user_roles::Relation::AppRoles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::app_user_roles::Relation::AppUsers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
