//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app_role_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_permissions::Entity",
        from = "Column::PermissionId",
        to = "super::app_permissions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppPermissions,
    #[sea_orm(
        belongs_to = "super::app_roles::Entity",
        from = "Column::RoleId",
        to = "super::app_roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppRoles,
}

impl Related<super::app_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppPermissions.def()
    }
}

impl Related<super::app_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
