//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "app_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub code: String,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_role_permissions::Entity")]
    AppRolePermissions,
    #[sea_orm(has_many = "super::app_user_roles::Entity")]
    AppUserRoles,
}

impl Related<super::app_role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRolePermissions.def()
    }
}

impl Related<super::app_user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUserRoles.def()
    }
}

impl Related<super::app_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_role_permissions::Relation::AppPermissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::app_role_permissions::Relation::AppRoles.def().rev())
    }
}

impl Related<super::app_users::Entity> for Entity {
    fn to() -> RelationDef {
        super::app_user_roles::Relation::AppUsers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::app_user_roles::Relation::AppRoles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
