//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod admin_menus;
pub mod admin_permissions;
pub mod admin_role_permissions;
pub mod admin_roles;
pub mod admin_user_roles;
pub mod admin_users;
pub mod app_permissions;
pub mod app_role_permissions;
pub mod app_roles;
pub mod app_user_roles;
pub mod app_users;
