//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::{
    menus::Entity as Menus, permissions::Entity as Permissions,
    role_permissions::Entity as RolePermissions, roles::Entity as Roles,
    user_roles::Entity as UserRoles,
};
