//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::{
    admin_menus::Entity as AdminMenus, admin_permissions::Entity as AdminPermissions,
    admin_role_permissions::Entity as AdminRolePermissions, admin_roles::Entity as AdminRoles,
    admin_user_roles::Entity as AdminUserRoles, admin_users::Entity as AdminUsers,
    app_permissions::Entity as AppPermissions, app_role_permissions::Entity as AppRolePermissions,
    app_roles::Entity as AppRoles, app_user_roles::Entity as AppUserRoles,
    app_users::Entity as AppUsers,
};
