[http]
port = 19878

[jwt]
public_key_pem = "ed25519 public key in PEM format"
issuer = "test"
audience = "test"


[[db]]
name = "default"
url = "postgres://postgres:123456@localhost:15432/sdk"
max_connections = 10
min_connections = 1
connect_timeout = 30
idle_timeout = 600
sql_logging = false


